gesture image capture
mohdomama/VirtualStylus pull request #1
Opened 2018-10-03 16:31 UTC by proishan11

Code to capture images for a given gesture class.

2018-10-05 02:04 UTC, mohdomama requested changes
There should be an option to add a string before image name.
Enable `anaconda` in sublime. Follow `pep8`
Move the script in `util` folder

2018-10-05 18:50 UTC, RJ722 commented on CaptureImage.py
> +		if(cv2.waitKey(0) & 0xFF == ord('q')):
Why on earth is there a newline between every two lines?

2018-10-05 18:55 UTC, RJ722 commented on CaptureImage.py
> +		path = "./"+rootName
Use `os.path.join`

2018-10-05 18:55 UTC, RJ722 commented on CaptureImage.py
> +		print(path)
No need of printing the path. If you strictly need to log the path, use the `logging` module instead.

2018-10-05 18:55 UTC, RJ722 commented on CaptureImage.py
> +		cv2.imwrite(path+"/{}.jpg".format(currentFrame), frame)
Again, use `os.path.join`.

2018-10-05 18:55 UTC, RJ722 commented on CaptureImage.py
> +		print('Cannot create the directory')
Are you sure that you shall allow all the code to run, although an exception has been thrown here. You might want to exit the script here (using something like `sys.exit(1)`.

Also, change the error message to be more clear: "Directory already exists."

2018-10-05 18:57 UTC, RJ722 commented
Also, change your commit message to say something more useful than "gesture image capture"

2018-10-05 18:59 UTC, RJ722 commented
This PR was created from your master branch. You should *never* ever do that. Your master branch should always remain in sync with `upstream/master`. Always, create a new branch for different features/PR's. This will help you to:
- Revert back to master in case something goes wrong.
- Work on more than one PR's at a time.

2018-10-08 11:13 UTC, mohdomama commented
Closing. Alternate PR will be sent for this.

2018-10-08 11:14 UTC, closed without merging